name: Deploy Python Code to Lambda

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies (if any)
        run: |
          python3 -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the environment
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install the dependencies from requirements.txt

      - name: Package the Lambda code
        run: |
          # Zip the dependencies
          # If you have multiple files or dependencies, you can zip them
          zip -r function.zip . -x "*.git*" -x "venv/*"

      - name: Deploy to Lambda
        run: |
          # Deploy to Lambda using the AWS CLI
          aws lambda update-function-code \
            --function-name pb_Lambda \
            --zip-file fileb://function.zip
