name: Deploy Python Code to Lambda

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Set up AWS credentials using GitHub Secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install dependencies and package them with the Lambda function code
      - name: Install dependencies (if any)
        run: |
          # Not specifically required
          # Create a temporary directory for the dependencies
          mkdir -p package

          # Install dependencies from requirements.txt into the 'package' directory
          pip install -r requirements.txt -t package/

      # Package the Lambda function and dependencies into a zip file
      - name: Package the Lambda code
        run: |
          # Create the deployment package (zip file)
          cd package
          zip -r ../function.zip .
          
          # Add your lambda function code to the deployment package
          cd ..
          zip -r function.zip lambda_function.py

      # Attach the S3 Full Access Policy to Lambda Execution Role
      - name: Add IAM Policy to Lambda Role
        run: |
          aws iam put-role-policy \
            --role-name pb_Lambda-role-p701530o \
            --policy-name S3FullAccess \
            --policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject","s3:ListBucket"],"Resource":["arn:aws:s3:::sn-bd-test","arn:aws:s3:::sn-bd-test/*"]}]}'

      # Attach the AWS SDK for Pandas Layer to Lambda function
      - name: Attach AWS SDK for Pandas Layer to Lambda
        run: |
          aws lambda update-function-configuration \
            --function-name pb_Lambda \
            --layers arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312:16

      # Deploy the Lambda function code
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name pb_Lambda \
            --zip-file fileb://function.zip
      # Test Lambda Function now
      - name: Test Lambda Function
        run: |
          # Trigger a test event to invoke Lambda function
          response=$(aws lambda invoke \
            --function-name pb_Lambda \
            
            response.json)

          # Print the output of the Lambda invocation
          echo "Lambda Response: $response"
          cat response.json
